name: Deploy Dockerized Python App

on:
  push
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run Docker container
        run: docker run  --rm --publish 5000:5000 frolvlad/flask-restplus-server-example

      - name: Test Deployed App
        run: |
          # Aguarde alguns segundos para garantir que a aplicação está em execução
          sleep 10
          # Teste o endpoint usando curl
          curl http://127.0.0.1:5000/api/v1/
